language: minimal
dist: xenial
addons:
  apt:
    packages:
    - docker-ce
before_install: ./.travis.before_install.sh 
script: ./.travis.script.sh
env:
  global:
  - secure: Qo3LzheQusT/0i4SUa01v+CI3Mj2v7FSwsfxLE+gxK4YlvFcyJdRAyr7LF+GsfQVETCDC6fQhvwDoTXi3uvPDUadlybpwaFnxrrBOL+p79vXm1zMGpms2PoE+Bippv6ubE0+c2rCTEdQs0q9ncstY8DpPQjdB65ScPlYGeG9N1Tty28DHwg9hMQfHqcbz0aQT5I3te4gkyddslmEFwdg+5YE0GSdRB5JS9rtcI6aEfeZd0XrSMW0nzDgWuZ0qT1WWaYxG5GmVp2konBYMS1ISV4rFNY5U/UZaVRsSWx0/VFS4akawyNlrRNie3k8q5TSg+NxoL81v3iDMRr4uoDF84ELsUf/AOibDVEF64chkP+7hBY8ARqvPI1IbqFyGeR70lAvum5RPPgpJTnoLDLl/YH6CB1U6YhWnADEnYt1uipLZBIUht3CZkaAu9yYYwQtjmBDoaHeZzLz97oBvhFCCK+sacjmnXeYSXjHeeiblMZPU5UodN8j2xRFFlHbMT0I68FgRvQJmCyQEkDPi9a4jn1/dnQ0E/A1+p8t9LkGBPKN1A3REZipY6z24TADyuyHTE4tYcwcClv1k0AMnPQfpCWu9nfJ1BJYNdlnW/cJpx16g6tpZXntXDny8SmcbK9P9pP5SCsvSMMDaeyOhni/ZCkSimy6LcgM4gp+ZSBLJ50=
  - secure: BF1LEcBsofV27EUUDDscq6mEGvPbsxwncv8RDpHwzQiY2JHBSzI6wrtB1NpGPajfgU9L0jv2xOBgGjEvZLlkQovueg5rSyzPF6ckJFbZ2h69alxC5R7gfbzyeKSTu2+s7yHo+RAXKlwb6/mgyJyBBo5ot6BIhYzdHCA08AghqSQzjZzQuB3AZkrBFSCuNSXVjQliWcTSN7LQefqaR7YXTGLcngmyR6bIpAGPt5DTOlbloFBKPXE39LdSuJwoHTgeFduNSv6j8FIQbg+CoTrJM06NUpdgyvH/liJxV7WrW6RcbgTszDP/B7C8DhbUP/St2vWsivK+AhlaGgHw7cs4TetQ5+yfxIPG8mz6YPVxXkKvIX2bld/ID3Kbttf00sHXwllwrm7qLbbKjl9BA0tMGAHSTXK47FoEwRRLL7a3FFoE9o5HlA1RqwfRyghsi9o7YcA0F783F+H2t0Pc/yaRV2xUU4HQnu41im87v3F559l0HPVLWLbXCecxLIASdvLKbOGmJVb8OfXLSn8auFuXwNbBAusOxPiyE/2nBKrjUa2zn+zyn3BWyu4KvLl7Rmh0TbyqwaNYHR88ZKNPb6WU5OaKHex37LzVrcmAtbDbizLVuZALf1Ly3KZXy49Kp+30Y95EKQ3lktMwCf1JeQIUMhYEnL4WY0VtelETOaQuc5A=
